quarkus.application.name=template-java-quarkus

quarkus.banner.enabled=false

quarkus.http.port=8080
quarkus.http.root-path=/api

quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:file:./.db/h2/demo
quarkus.datasource.username=admin
quarkus.datasource.password=admin

quarkus.hibernate-orm.schema-management.strategy=update
